# Generated by Django 3.2.8 on 2021-11-21 11:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0002_auto_20211024_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='last_date',
            field=models.DateField(default=datetime.date(2021, 12, 6), null=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='posted_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
