# Generated by Django 3.2.8 on 2021-11-28 07:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0003_auto_20211121_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employer.companyprofile'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='last_date',
            field=models.DateField(default=datetime.date(2021, 12, 13), null=True),
        ),
    ]
